# Generated by Django 5.1.2 on 2024-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrecord',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='violationrecord',
            name='violation_article',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='violationrecord',
            name='violation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
